name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Instala as dependencias
        run: npm install

      - name: Build do projeto
        run: npm run build

      - name: Upload de artefatos para o deploy
        uses: actions/upload-artifact@v3
        with:
          name: dist-artifacts # Name the artifact
          path: dist # Folder where your static files are generated

      - name: Deploy ao GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          artifact_name: dist-artifacts # Name of the uploaded artifact
